# Capstone Project: Create a Customer Segmentation Report for Arvato Financial Services

In this project, you will analyze demographics data for customers of a mail-order sales company in Germany, comparing it against demographics information for the general population. You'll use unsupervised learning techniques to perform customer segmentation, identifying the parts of the population that best describe the core customer base of the company. Then, you'll apply what you've learned on a third dataset with demographics information for targets of a marketing campaign for the company, and use a model to predict which individuals are most likely to convert into becoming customers for the company. The data that you will use has been provided by our partners at Bertelsmann Arvato Analytics, and represents a real-life data science task.

The versions of those two datasets used in this project will include many more features and has not been pre-cleaned. You are also free to choose whatever approach you'd like to analyzing the data rather than follow pre-determined steps. In your work on this project, make sure that you carefully document your steps and decisions, since your main deliverable for this project will be a blog post reporting your findings.

In [49]:
# import libraries here; add more as necessary
import numpy as np
import pandas as pd
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 999)
pd.set_option('display.max_colwidth', None)

import os

import matplotlib.pyplot as plt
import seaborn as sns

# magic word for producing visualizations in notebook
%matplotlib inline

## Part 0: Get to Know the Data

There are four data files associated with this project:

1) `Udacity_AZDIAS_052018.csv`: Demographics data for the general population of Germany; 891 211 persons (rows) x 366 features (columns).
2) `Udacity_CUSTOMERS_052018.csv`: Demographics data for customers of a mail-order company; 191 652 persons (rows) x 369 features (columns).
3) `Udacity_MAILOUT_052018_TRAIN.csv`: Demographics data for individuals who were targets of a marketing campaign; 42 982 persons (rows) x 367 (columns).
4) `Udacity_MAILOUT_052018_TEST.csv`: Demographics data for individuals who were targets of a marketing campaign; 42 833 persons (rows) x 366 (columns).

#############<br>
Whereas the first two files are used to find the relevant part of the general population which is more likely to be part of the mail-order company's main customer base, the other two files (3 & 4) are the basis to build a model to predict if the individual should be targeted in a mail out campaign.

## Load the data

In [46]:
# load in the data
root_path = os.path.dirname(os.getcwd())


azdias = pd.read_csv(rf'{root_path}\07_Project_Capstone_Arvato-Bertelsmann\data\Udacity_AZDIAS_052018.csv', sep=';')
customers = pd.read_csv(rf'{root_path}\07_Project_Capstone_Arvato-Bertelsmann\data\Udacity_CUSTOMERS_052018.csv', sep=';')

col_description = pd.read_excel(rf'{root_path}\07_Project_Capstone_Arvato-Bertelsmann\data\DIAS Attributes - Values 2017.xlsx', sheet_name="tbl_col_description")

C:\Users\z635177\AppData\Local\Temp\ipykernel_15036\760149371.py:5: DtypeWarning: Columns (18,19) have mixed types. Specify dtype option on import or set low_memory=False.
  azdias = pd.read_csv(rf'{root_path}\07_Project_Capstone_Arvato-Bertelsmann\data\Udacity_AZDIAS_052018.csv', sep=';')
C:\Users\z635177\AppData\Local\Temp\ipykernel_15036\760149371.py:6: DtypeWarning: Columns (18,19) have mixed types. Specify dtype option on import or set low_memory=False.
  customers = pd.read_csv(rf'{root_path}\07_Project_Capstone_Arvato-Bertelsmann\data\Udacity_CUSTOMERS_052018.csv', sep=';')


## General understanding of the data

First of all, it is important to get solid understanding which columns are present in the dataset(s) and be aware of their meaning.<br>
The two first dataset have only minor differences concerning the columns: The customers dataset has the following three columns additionally to the columns set of the dataset of the general population (azdias). 

In [47]:
np.setdiff1d(
    np.array(customers.columns),
    np.array(azdias.columns),
    assume_unique=True
)

array(['PRODUCT_GROUP', 'CUSTOMER_GROUP', 'ONLINE_PURCHASE'], dtype=object)

The following dataframe shows the column description provided by Arvato to get a better logical understanding of the data:

In [55]:
description_df = pd.merge(left = customers.describe(include = "all").T, right = col_description, left_index = True, right_on = "Attribute", how = "left")

In [56]:
description_df

count unique                  top    freq         mean  \
NaN    191652.0    NaN                  NaN     NaN      95826.5   
0.0    191652.0    NaN                  NaN     NaN     0.344359   
NaN    145056.0    NaN                  NaN     NaN     1.747525   
2.0    145056.0    NaN                  NaN     NaN    11.352009   
NaN     11766.0    NaN                  NaN     NaN    12.337243   
NaN      5100.0    NaN                  NaN     NaN    13.672353   
NaN      1275.0    NaN                  NaN     NaN    14.647059   
NaN       236.0    NaN                  NaN     NaN    15.377119   
NaN    139810.0    NaN                  NaN     NaN    10.331579   
4.0    141725.0    NaN                  NaN     NaN     4.965863   
5.0    139542.0    NaN                  NaN     NaN     0.067413   
NaN    145056.0    NaN                  NaN     NaN     0.136402   
6.0    145056.0    NaN                  NaN     NaN     2.267828   
NaN    141725.0    NaN                  NaN     NaN     4.701288   
7.0    145056.0    NaN                  NaN     NaN     0.020392   
NaN    141176.0    NaN                  NaN     NaN      2.82485   
8.0    141693.0    NaN                  NaN     NaN     4.301758   
11.0     141224     45                   2D   11208          NaN   
10.0     141224     19                    2   17574          NaN   
NaN      141224     43                   14   14708          NaN   
13.0   188439.0    NaN                  NaN     NaN     3.677928   
NaN    188439.0    NaN                  NaN     NaN      4.00994   
NaN    188439.0    NaN                  NaN     NaN     2.665441   
NaN    188439.0    NaN                  NaN     NaN      2.54849   
NaN    188439.0    NaN                  NaN     NaN     4.516369   
NaN    188439.0    NaN                  NaN     NaN     4.415317   
NaN    188439.0    NaN                  NaN     NaN     4.519956   
NaN    188439.0    NaN                  NaN     NaN     4.538838   
14.0   191652.0    NaN                  NaN     NaN      0.09104   
15.0   191652.0    NaN                  NaN     NaN     0.159524   
16.0   191652.0    NaN                  NaN     NaN     9.367599   
NaN    191652.0    NaN                  NaN     NaN     0.646166   
NaN    191652.0    NaN                  NaN     NaN     0.424478   
NaN    191652.0    NaN                  NaN     NaN      0.13297   
20.0   191652.0    NaN                  NaN     NaN     9.866472   
21.0   191652.0    NaN                  NaN     NaN     9.600646   
22.0   143955.0    NaN                  NaN     NaN     0.462019   
NaN    191652.0    NaN                  NaN     NaN     0.444477   
NaN    191652.0    NaN                  NaN     NaN     0.978727   
NaN    191652.0    NaN                  NaN     NaN      1.52778   
NaN    191652.0    NaN                  NaN     NaN     0.998565   
NaN    191652.0    NaN                  NaN     NaN     0.538492   
NaN    191652.0    NaN                  NaN     NaN     2.443987   
NaN    191652.0    NaN                  NaN     NaN     0.218265   
NaN    191652.0    NaN                  NaN     NaN     0.757999   
NaN    191652.0    NaN                  NaN     NaN     0.474266   
NaN    191652.0    NaN                  NaN     NaN     0.688414   
NaN    191652.0    NaN                  NaN     NaN     0.344525   
34.0   191652.0    NaN                  NaN     NaN     0.937679   
35.0   191652.0    NaN                  NaN     NaN     1.438581   
36.0   191652.0    NaN                  NaN     NaN     6.529496   
37.0   191652.0    NaN                  NaN     NaN     8.412435   
38.0   191652.0    NaN                  NaN     NaN     7.445714   
39.0   143955.0    NaN                  NaN     NaN     3.522879   
NaN    191652.0    NaN                  NaN     NaN     1.535257   
NaN    191652.0    NaN                  NaN     NaN     1.537031   
NaN    191652.0    NaN                  NaN     NaN     1.083516   
43.0   143955.0    NaN                  NaN     NaN     3.027654  

Get a deeper grasp of the data at hand by investigating specific records:

In [41]:
customers.head(3)

LNR  AGER_TYP  AKT_DAT_KL  ALTER_HH  ALTER_KIND1  ALTER_KIND2  \
0    9626         2         1.0      10.0          NaN          NaN   
1    9628        -1         9.0      11.0          NaN          NaN   
2  143872        -1         1.0       6.0          NaN          NaN   

   ALTER_KIND3  ALTER_KIND4  ALTERSKATEGORIE_FEIN  ANZ_HAUSHALTE_AKTIV  \
0          NaN          NaN                  10.0                  1.0   
1          NaN          NaN                   NaN                  NaN   
2          NaN          NaN                   0.0                  1.0   

   ANZ_HH_TITEL  ANZ_KINDER  ANZ_PERSONEN  ANZ_STATISTISCHE_HAUSHALTE  \
0           0.0         0.0           2.0                         1.0   
1           NaN         0.0           3.0                         NaN   
2           0.0         0.0           1.0                         1.0   

   ANZ_TITEL  ARBEIT  BALLRAUM CAMEO_DEU_2015 CAMEO_DEUG_2015 CAMEO_INTL_2015  \
0        0.0     1.0       3.0             1A             1.0            13.0   
1        0.0     NaN       NaN            NaN             NaN             NaN   
2        0.0     3.0       7.0             5D             5.0            34.0   

   CJT_GESAMTTYP  CJT_KATALOGNUTZER  CJT_TYP_1  CJT_TYP_2  CJT_TYP_3  \
0            5.0                4.0        1.0        1.0        5.0   
1            NaN                NaN        NaN        NaN        NaN   
2            2.0                5.0        2.0        2.0        5.0   

   CJT_TYP_4  CJT_TYP_5  CJT_TYP_6  D19_BANKEN_ANZ_12  D19_BANKEN_ANZ_24  \
0        5.0        5.0        5.0                  0                  0   
1        NaN        NaN        NaN                  0                  1   
2        5.0        5.0        5.0                  0                  0   

   D19_BANKEN_DATUM  D19_BANKEN_DIREKT  D19_BANKEN_GROSS  D19_BANKEN_LOKAL  \
0                10                  0                 0                 0   
1                 6                  0                 5                 0   
2                10                  0                 0                 0   

   D19_BANKEN_OFFLINE_DATUM  D19_BANKEN_ONLINE_DATUM  \
0                        10                       10   
1                        10                       10   
2                        10                       10   

   D19_BANKEN_ONLINE_QUOTE_12  D19_BANKEN_REST  D19_BEKLEIDUNG_GEH  \
0                         0.0                0                   0   
1                         0.0                6                   0   
2                         0.0                0                   0   

   D19_BEKLEIDUNG_REST  D19_BILDUNG  D19_BIO_OEKO  D19_BUCH_CD  \
0                    0            0             0            6   
1                    0            0             0            0   
2                    0            6             0            0   

   D19_DIGIT_SERV  D19_DROGERIEARTIKEL  D19_ENERGIE  D19_FREIZEIT  D19_GARTEN  \
0               0                    0            0             0           0   
1               0                    6            0             0           0   
2               0                    0            0             0           0   

   D19_GESAMT_ANZ_12  D19_GESAMT_ANZ_24  D19_GESAMT_DATUM  \
0                  0                  0                 9   
1                  0                  1                 6   
2                  0                  0                10   

   D19_GESAMT_OFFLINE_DATUM  D19_GESAMT_ONLINE_DATUM  \
0                         9                       10   
1                        10                        9   
2                        10                       10   

   D19_GESAMT_ONLINE_QUOTE_12  D19_HANDWERK  D19_HAUS_DEKO  D19_KINDERARTIKEL  \
0                         0.0             0              6                  0   
1                         0.0             0              0                  0   
2                         0.0             0              0                  0   

   D19_K

In [42]:
customers.describe(include = "all")

LNR       AGER_TYP     AKT_DAT_KL       ALTER_HH  \
count   191652.000000  191652.000000  145056.000000  145056.000000   
unique            NaN            NaN            NaN            NaN   
top               NaN            NaN            NaN            NaN   
freq              NaN            NaN            NaN            NaN   
mean     95826.500000       0.344359       1.747525      11.352009   
std      55325.311233       1.391672       1.966334       6.275026   
min          1.000000      -1.000000       1.000000       0.000000   
25%      47913.750000      -1.000000       1.000000       8.000000   
50%      95826.500000       0.000000       1.000000      11.000000   
75%     143739.250000       2.000000       1.000000      16.000000   
max     191652.000000       3.000000       9.000000      21.000000   

         ALTER_KIND1  ALTER_KIND2  ALTER_KIND3  ALTER_KIND4  \
count   11766.000000  5100.000000  1275.000000   236.000000   
unique           NaN          NaN          NaN          NaN   
top              NaN          NaN          NaN          NaN   
freq             NaN          NaN          NaN          NaN   
mean       12.337243    13.672353    14.647059    15.377119   
std         4.006050     3.243335     2.753787     2.307653   
min         2.000000     2.000000     5.000000     8.000000   
25%         9.000000    11.000000    13.000000    14.000000   
50%        13.000000    14.000000    15.000000    16.000000   
75%        16.000000    16.000000    17.000000    17.000000   
max        18.000000    18.000000    18.000000    18.000000   

        ALTERSKATEGORIE_FEIN  ANZ_HAUSHALTE_AKTIV   ANZ_HH_TITEL  \
count          139810.000000        141725.000000  139542.000000   
unique                   NaN                  NaN            NaN   
top                      NaN                  NaN            NaN   
freq                     NaN                  NaN            NaN   
mean               10.331579             4.965863       0.067413   
std                 4.134828            14.309694       0.545576   
min                 0.000000             0.000000       0.000000   
25%                 9.000000             1.000000       0.000000   
50%                10.000000             1.000000       0.000000   
75%                13.000000             4.000000       0.000000   
max                25.000000           523.000000      23.000000   

           ANZ_KINDER   ANZ_PERSONEN  ANZ_STATISTISCHE_HAUSHALTE  \
count   145056.000000  145056.000000               141725.000000   
unique            NaN            NaN                         NaN   
top               NaN            NaN                         NaN   
freq              NaN            NaN                         NaN   
mean         0.136402       2.267828                    4.701288   
std          0.493249       1.390620                   14.184081   
min          0.000000       0.000000                    0.000000   
25%          0.000000       1.000000                    1.000000   
50%          0.000000       2.000000                    1.000000   
75%          0.000000       3.000000                    3.000000   
max          8.000000      21.000000                  375.000000   

            ANZ_TITEL         ARBEIT       BALLRAUM CAMEO_DEU_2015  \
count   145056.000000  141176.000000  141693.000000         141224   
unique            NaN            NaN            NaN             45   
top               NaN            NaN            NaN             2D   
freq              NaN            NaN            NaN          11208   
mean         0.020392       2.824850       4.301758            NaN   
std          0.152234       1.012415       2.114614            NaN   
min          0.000000       1.000000       1.000000            NaN   
25%          0.000000       2.000000       2.000000            NaN   
50%          0.000000       3.000000       5.000000            NaN   
75%          0.000000       4.000000       6.000000            NaN   
max          5.0

In [17]:
grouped = azdias.dtypes.groupby(azdias.dtypes)

for g in grouped.groups.keys():
    print(f"{g}: {grouped.groups[g].tolist()}")

int64: ['LNR', 'AGER_TYP', 'D19_BANKEN_ANZ_12', 'D19_BANKEN_ANZ_24', 'D19_BANKEN_DATUM', 'D19_BANKEN_DIREKT', 'D19_BANKEN_GROSS', 'D19_BANKEN_LOKAL', 'D19_BANKEN_OFFLINE_DATUM', 'D19_BANKEN_ONLINE_DATUM', 'D19_BANKEN_REST', 'D19_BEKLEIDUNG_GEH', 'D19_BEKLEIDUNG_REST', 'D19_BILDUNG', 'D19_BIO_OEKO', 'D19_BUCH_CD', 'D19_DIGIT_SERV', 'D19_DROGERIEARTIKEL', 'D19_ENERGIE', 'D19_FREIZEIT', 'D19_GARTEN', 'D19_GESAMT_ANZ_12', 'D19_GESAMT_ANZ_24', 'D19_GESAMT_DATUM', 'D19_GESAMT_OFFLINE_DATUM', 'D19_GESAMT_ONLINE_DATUM', 'D19_HANDWERK', 'D19_HAUS_DEKO', 'D19_KINDERARTIKEL', 'D19_KONSUMTYP_MAX', 'D19_KOSMETIK', 'D19_LEBENSMITTEL', 'D19_NAHRUNGSERGAENZUNG', 'D19_RATGEBER', 'D19_REISEN', 'D19_SAMMELARTIKEL', 'D19_SCHUHE', 'D19_SONSTIGE', 'D19_TECHNIK', 'D19_TELKO_ANZ_12', 'D19_TELKO_ANZ_24', 'D19_TELKO_DATUM', 'D19_TELKO_MOBILE', 'D19_TELKO_OFFLINE_DATUM', 'D19_TELKO_ONLINE_DATUM', 'D19_TELKO_REST', 'D19_TIERARTIKEL', 'D19_VERSAND_ANZ_12', 'D19_VERSAND_ANZ_24', 'D19_VERSAND_DATUM', 'D19_VERSAND_OF

In [20]:
azdias.info(
    verbose = True,
    memory_usage="deep",
    show_counts=True,
)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891221 entries, 0 to 891220
Data columns (total 366 columns):
 #    Column                       Non-Null Count   Dtype  
---   ------                       --------------   -----  
 0    LNR                          891221 non-null  int64  
 1    AGER_TYP                     891221 non-null  int64  
 2    AKT_DAT_KL                   817722 non-null  float64
 3    ALTER_HH                     817722 non-null  float64
 4    ALTER_KIND1                  81058 non-null   float64
 5    ALTER_KIND2                  29499 non-null   float64
 6    ALTER_KIND3                  6170 non-null    float64
 7    ALTER_KIND4                  1205 non-null    float64
 8    ALTERSKATEGORIE_FEIN         628274 non-null  float64
 9    ANZ_HAUSHALTE_AKTIV          798073 non-null  float64
 10   ANZ_HH_TITEL                 794213 non-null  float64
 11   ANZ_KINDER                   817722 non-null  float64
 12   ANZ_PERSONEN                 817722 non-nu

In [5]:
customers.info(
    verbose = True,
    memory_usage="deep",
    show_counts=True,
)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 191652 entries, 0 to 191651
Data columns (total 369 columns):
 #    Column                       Non-Null Count   Dtype  
---   ------                       --------------   -----  
 0    LNR                          191652 non-null  int64  
 1    AGER_TYP                     191652 non-null  int64  
 2    AKT_DAT_KL                   145056 non-null  float64
 3    ALTER_HH                     145056 non-null  float64
 4    ALTER_KIND1                  11766 non-null   float64
 5    ALTER_KIND2                  5100 non-null    float64
 6    ALTER_KIND3                  1275 non-null    float64
 7    ALTER_KIND4                  236 non-null     float64
 8    ALTERSKATEGORIE_FEIN         139810 non-null  float64
 9    ANZ_HAUSHALTE_AKTIV          141725 non-null  float64
 10   ANZ_HH_TITEL                 139542 non-null  float64
 11   ANZ_KINDER                   145056 non-null  float64
 12   ANZ_PERSONEN                 145056 non-nu

In [22]:
def create_summary(df, n):
    """Create a summary df for a better understanding of the data

    Args:
        df (_type_): _description_
        n (_type_): _description_
    """

    df_ = pd.concat([
        df.dtypes,
        df.isnull().sum(),
        df.isnull().sum() / azdias.shape[0],
        df.nunique(),
    ], axis = 1).rename({0:"dtype", 1: "missing abs.", 2: "missing perc.", 3: "nunique"}, axis = 1).sort_values(by = "missing perc.", ascending=False).head(n)

    return df_

In [23]:
create_summary(azdias, 10)

dtype  missing abs.  missing perc.  nunique
ALTER_KIND4                float64        890016       0.998648       12
ALTER_KIND3                float64        885051       0.993077       15
ALTER_KIND2                float64        861722       0.966900       17
ALTER_KIND1                float64        810163       0.909048       17
EXTSEL992                  float64        654153       0.733996       56
KK_KUNDENTYP               float64        584612       0.655967        6
ALTERSKATEGORIE_FEIN       float64        262947       0.295041       26
D19_TELKO_ONLINE_QUOTE_12  float64        257113       0.288495        5
D19_SOZIALES               float64        257113       0.288495        6
D19_LETZTER_KAUF_BRANCHE    object        257113       0.288495       35

In [24]:
create_summary(customers, 10)

dtype  missing abs.  missing perc.  nunique
ALTER_KIND4   float64        191416       0.214779       10
ALTER_KIND3   float64        190377       0.213614       14
ALTER_KIND2   float64        186552       0.209322       17
ALTER_KIND1   float64        179886       0.201842       17
KK_KUNDENTYP  float64        111937       0.125600        6
EXTSEL992     float64         85283       0.095692       56
KBA05_ANHANG  float64         55980       0.062813        5
MOBI_REGIO    float64         55980       0.062813        6
KBA05_SEG2    float64         55980       0.062813        6
KBA05_SEG10   float64         55980       0.062813        6

## Part 1: Customer Segmentation Report

The main bulk of your analysis will come in this part of the project. Here, you should use unsupervised learning techniques to describe the relationship between the demographics of the company's existing customers and the general population of Germany. By the end of this part, you should be able to describe parts of the general population that are more likely to be part of the mail-order company's main customer base, and which parts of the general population are less so.

## Part 2: Supervised Learning Model

Now that you've found which parts of the population are more likely to be customers of the mail-order company, it's time to build a prediction model. Each of the rows in the "MAILOUT" data files represents an individual that was targeted for a mailout campaign. Ideally, we should be able to use the demographic information from each individual to decide whether or not it will be worth it to include that person in the campaign.

The "MAILOUT" data has been split into two approximately equal parts, each with almost 43 000 data rows. In this part, you can verify your model with the "TRAIN" partition, which includes a column, "RESPONSE", that states whether or not a person became a customer of the company following the campaign. In the next part, you'll need to create predictions on the "TEST" partition, where the "RESPONSE" column has been withheld.

In [ ]:
mailout_train = pd.read_csv('../../data/Term2/capstone/arvato_data/Udacity_MAILOUT_052018_TRAIN.csv', sep=';')

There are four data files associated with this project:

- `Udacity_AZDIAS_052018.csv`: Demographics data for the general population of Germany; 891 211 persons (rows) x 366 features (columns).
- `Udacity_CUSTOMERS_052018.csv`: Demographics data for customers of a mail-order company; 191 652 persons (rows) x 369 features (columns).
- `Udacity_MAILOUT_052018_TRAIN.csv`: Demographics data for individuals who were targets of a marketing campaign; 42 982 persons (rows) x 367 (columns).
- `Udacity_MAILOUT_052018_TEST.csv`: Demographics data for individuals who were targets of a marketing campaign; 42 833 persons (rows) x 366 (columns).

Each row of the demographics files represents a single person, but also includes information outside of individuals, including information about their household, building, and neighborhood. Use the information from the first two files to figure out how customers ("CUSTOMERS") are similar to or differ from the general population at large ("AZDIAS"), then use your analysis to make predictions on the other two files ("MAILOUT"), predicting which recipients are most likely to become a customer for the mail-order company.

The "CUSTOMERS" file contains three extra columns ('CUSTOMER_GROUP', 'ONLINE_PURCHASE', and 'PRODUCT_GROUP'), which provide broad information about the customers depicted in the file. The original "MAILOUT" file included one additional column, "RESPONSE", which indicated whether or not each recipient became a customer of the company. For the "TRAIN" subset, this column has been retained, but in the "TEST" subset it has been removed; it is against that withheld column that your final predictions will be assessed in the Kaggle competition.

Otherwise, all of the remaining columns are the same between the three data files. For more information about the columns depicted in the files, you can refer to two Excel spreadsheets provided in the workspace. [One of them](./DIAS Information Levels - Attributes 2017.xlsx) is a top-level list of attributes and descriptions, organized by informational category. [The other](./DIAS Attributes - Values 2017.xlsx) is a detailed mapping of data values for each feature in alphabetical order.

In the below cell, we've provided some initial code to load in the first two datasets. Note for all of the `.csv` data files in this project that they're semicolon (`;`) delimited, so an additional argument in the [`read_csv()`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html) call has been included to read in the data properly. Also, considering the size of the datasets, it may take some time for them to load completely.

You'll notice when the data is loaded in that a warning message will immediately pop up. Before you really start digging into the modeling and analysis, you're going to need to perform some cleaning. Take some time to browse the structure of the data and look over the informational spreadsheets to understand the data values. Make some decisions on which features to keep, which features to drop, and if any revisions need to be made on data formats. It'll be a good idea to create a function with pre-processing steps, since you'll need to clean all of the datasets before you work with them.